<?php

namespace ContainerQ4yxkBc;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMongoDBManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\MongoDBManager' shared autowired service.
     *
     * @return \App\Service\MongoDBManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MongoDBManager.php';

        return $container->services['App\\Service\\MongoDBManager'] = new \App\Service\MongoDBManager();
    }
}
